server:
  port:8081

spring:
    application:
      name:
        User-Service
    datasource:
      url: jdbc:postgresql://localhost:5432/Fitness_user
      username:
        postgres
      password: root987@
    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
